project:
  type: website
  output-dir: .

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - projects.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false




